public class StringArrayTest {
    public static void generateStringArray(
        
        // Create a list and add elements to it in one step
        String[] arrays = new List<String> { 'Test 1', 'Test 2', 'Test 3' };
        
        // Get elements from a list
        String array1 = moreArrays.get(0);
        String array2 = moreArrays[0];
        System.assertEquals(array1, array);
        
        // Iterate over a list to read elements
        for(Integer i : myInts) {
            System.debug(i);
        }
        
        String 
